version: '3.8'

services:
    app:
        build:
            context: . # Set the build context to the current directory
            dockerfile: Dockerfile
        working_dir: /app/
        ports:
            - '3000:3000'
        command: sh -c "yarn install && yarn build && yarn start"
